plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '5.1.+'
}

group = 'com.agro388mods'
version = '1.0.0'
sourceCompatibility = '17'
targetCompatibility = '17'

repositories {
    mavenCentral()
    maven { url = 'https://files.minecraftforge.net/maven' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-58.0.0'
}

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        client {
            workingDirectory project.file('run')
        }
    }
}
